CREATE TABLE "optic_contact_lens_chk" (
    "code"                           INTEGER PRIMARY KEY AUTOINCREMENT
   ,"contact_presc_code"             INTEGER
   ,"branch_code"                    INTEGER
   ,"account_code"                   INTEGER
   ,"account_type"                   TEXT NOT NULL
   ,"tested_eye"                     TEXT
   ,"trial_sct"                      TEXT
   ,"chk_comment"                    TEXT
   ,"chk_add"                        REAL
   ,"chk_va"                         TEXT
   ,"is_active"                      TEXT NOT NULL DEFAULT '1'
   ,"last_action"                    TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
   ,"lens_bc_1"                      REAL
   ,"lens_bc_2"                      REAL
   ,"lens_diam"                      REAL
   ,"lens_sph"                       TEXT
   ,"lens_cyl"                       TEXT
   ,"lens_ax"                        INTEGER
   ,"lens_add"                       REAL
   ,"or_sph"                         TEXT
   ,"or_cyl"                         TEXT
   ,"or_ax"                          INTEGER
   ,"res_sph"                        TEXT
   ,"res_cyl"                        TEXT
   ,"res_ax"                         INTEGER
   ,"lens_group"                     TEXT
   ,"lens_function"                  TEXT
   ,"chk_remark"                     TEXT
   ,"chk_ok"                         TEXT DEFAULT '0'
   ,"lens_type"                      TEXT
   ,"lens_turn_ax"                   INTEGER
   ,"lens_supplier"                  TEXT
   ,"lens_model"                     TEXT
   ,"item_code"                      INTEGER
);


CREATE TABLE "optic_contact_presc" (
    "code"                           INTEGER PRIMARY KEY AUTOINCREMENT
   ,"branch_code"                    INTEGER
   ,"account_code"                   INTEGER
   ,"account_type"                   TEXT NOT NULL
   ,"presc_date"                     TEXT
   ,"treatment_type"                 TEXT
   ,"cr_right_rv"                    REAL
   ,"cr_right_rh"                    REAL
   ,"cr_right_avg"                   REAL
   ,"cr_right_cyl"                   REAL
   ,"cr_right_ax"                    INTEGER
   ,"cr_left_rv"                     REAL
   ,"cr_left_rh"                     REAL
   ,"cr_left_avg"                    REAL
   ,"cr_left_cyl"                    REAL
   ,"cr_left_ax"                     INTEGER
   ,"sirmer_right"                   REAL
   ,"sirmer_right_but"               REAL
   ,"sirmer_left"                    REAL
   ,"sirmer_left_but"                REAL
   ,"tester_code"                    INTEGER
   ,"right_bc1"                      TEXT
   ,"right_bc2"                      TEXT
   ,"right_oz"                       TEXT
   ,"right_diam"                     REAL
   ,"right_sph"                      TEXT
   ,"right_cyl"                      TEXT
   ,"right_ax"                       INTEGER
   ,"right_va"                       TEXT
   ,"right_read"                     TEXT
   ,"right_j"                        TEXT
   ,"left_bc1"                       TEXT
   ,"left_bc2"                       TEXT
   ,"left_oz"                        TEXT
   ,"left_diam"                      REAL
   ,"left_sph"                       TEXT
   ,"left_cyl"                       TEXT
   ,"left_ax"                        INTEGER
   ,"left_va"                        TEXT
   ,"left_read"                      TEXT
   ,"left_j"                         TEXT
   ,"mid_va"                          TEXT
   ,"clean_sol"                      TEXT
   ,"dis_sol"                        TEXT
   ,"wash_sol"                       TEXT
   ,"lenses_color"                   TEXT
   ,"right_type"                     TEXT
   ,"right_manuf"                    TEXT
   ,"right_model"                    TEXT
   ,"left_type"                      TEXT
   ,"left_model"                     TEXT
   ,"left_manuf"                     TEXT
   ,"cornia_diam"                    REAL
   ,"pupil_distance"                 REAL
   ,"presc_remark"                   TEXT
   ,"order_date"                     TEXT
   ,"given_at"                       TEXT
   ,"is_active"                      TEXT NOT NULL DEFAULT '1'
   ,"last_action"                    TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
   ,"pupil_diameter"                 REAL
   ,"cr_right_ecc"                   REAL
   ,"cr_left_ecc"                    REAL
   ,"right_color"                    TEXT
   ,"left_color"                     TEXT
   ,"right_lens_code"                INTEGER
   ,"left_lens_code"                 INTEGER
   ,"right_lens_price"               REAL
   ,"left_lens_price"                REAL
   ,"right_qty"                      INTEGER
   ,"left_qty"                       INTEGER
   ,"right_order_qty"                INTEGER
   ,"left_order_qty"                 INTEGER
   ,"order_status"                   INTEGER
   ,"connection_code"                INTEGER
   ,"order_remarks"                  TEXT
   ,"lab_status"                     TEXT
   ,"num_payments"                   INTEGER
   ,"advance_sum"                    REAL
   ,"has_confirmation"               TEXT
   ,"order_iner_priority"            INTEGER
   ,"discount_sum"                   REAL
   ,"total_sum"                      REAL
   ,"giver_code"                     INTEGER
   ,"payments_rule"                  TEXT
   ,"promise_to_date"                TEXT
   ,"lab_status_sent"                TEXT
   ,"right_mater"                    TEXT
   ,"left_mater"                     TEXT
   ,"rlens_discount"                 REAL
   ,"llens_discount"                 REAL
   ,"create_time"                    TEXT
   ,"disconnect_finance"             TEXT
   ,"right_diagnostics"              TEXT
   ,"left_diagnostics"               TEXT
   ,"num_order"                      INTEGER
   ,"supplier_code"                  INTEGER
   ,"delivere_date"                  TEXT
   ,"advisor_code"                   INTEGER
   ,"supply_branch"                  INTEGER
   ,"right_qty_not_supply"           INTEGER
   ,"left_qty_not_supply"            INTEGER
   ,"stock_date"                     TEXT
);


CREATE TABLE "optic_exp_eyetests" (
    "code"                           INTEGER PRIMARY KEY AUTOINCREMENT
   ,"branch_code"                    INTEGER
   ,"account_code"                   INTEGER
   ,"account_type"                   TEXT NOT NULL
   ,"test_date"                      TEXT
   ,"tester_code"                    INTEGER
   ,"is_active"                      TEXT NOT NULL DEFAULT '1'
   ,"last_action"                    TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
   ,"old1_type"                      TEXT
   ,"old2_type"                      TEXT
   ,"old3_type"                      TEXT
   ,"old1_source"                    TEXT
   ,"old2_source"                    TEXT
   ,"old3_source"                    TEXT
   ,"old1_lens"                      TEXT
   ,"old2_lens"                      TEXT
   ,"old3_lens"                      TEXT
   ,"old1_remark"                    TEXT
   ,"old2_remark"                    TEXT
   ,"old3_remark"                    TEXT
   ,"test_reason"                    TEXT
   ,"old1_r_sph"                     TEXT
   ,"old2_r_sph"                     TEXT
   ,"old3_r_sph"                     TEXT
   ,"old1_r_cyl"                     TEXT
   ,"old2_r_cyl"                     TEXT
   ,"old3_r_cyl"                     TEXT
   ,"old1_r_ax"                      INTEGER
   ,"old2_r_ax"                      INTEGER
   ,"old3_r_ax"                      INTEGER
   ,"old1_r_prish"                   REAL
   ,"old2_r_prish"                   REAL
   ,"old3_r_prish"                   REAL
   ,"old1_r_baseh"                   TEXT
   ,"old2_r_baseh"                   TEXT
   ,"old3_r_baseh"                   TEXT
   ,"old1_r_prisv"                   REAL
   ,"old2_r_prisv"                   REAL
   ,"old3_r_prisv"                   REAL
   ,"old1_r_va"                      TEXT
   ,"old2_r_va"                      TEXT
   ,"old3_r_va"                      TEXT
   ,"old1_r_j"                       TEXT
   ,"old2_r_j"                       TEXT
   ,"old3_r_j"                       TEXT
   ,"old1_r_add"                     REAL
   ,"old2_r_add"                     REAL
   ,"old3_r_add"                     REAL
   ,"old1_r_pd"                      REAL
   ,"old2_r_pd"                      REAL
   ,"old3_r_pd"                      REAL
   ,"old1_l_sph"                     TEXT
   ,"old2_l_sph"                     TEXT
   ,"old3_l_sph"                     TEXT
   ,"old1_l_cyl"                     TEXT
   ,"old2_l_cyl"                     TEXT
   ,"old3_l_cyl"                     TEXT
   ,"old1_l_ax"                      INTEGER
   ,"old2_l_ax"                      INTEGER
   ,"old3_l_ax"                      INTEGER
   ,"old1_l_prish"                   REAL
   ,"old2_l_prish"                   REAL
   ,"old3_l_prish"                   REAL
   ,"old2_l_baseh"                   TEXT
   ,"old1_l_baseh"                   TEXT
   ,"old3_l_baseh"                   TEXT
   ,"old1_l_prisv"                   REAL
   ,"old2_l_prisv"                   REAL
   ,"old3_l_prisv"                   REAL
   ,"old1_l_basev"                   TEXT
   ,"old2_l_basev"                   TEXT
   ,"old3_l_basev"                   TEXT
   ,"old1_l_va"                      TEXT
   ,"old2_l_va"                      TEXT
   ,"old3_l_va"                      TEXT
   ,"old1_l_j"                       TEXT
   ,"old2_l_j"                       TEXT
   ,"old3_l_j"                       TEXT
   ,"old1_l_add"                     REAL
   ,"old2_l_add"                     REAL
   ,"old3_l_add"                     REAL
   ,"old1_l_pd"                      REAL
   ,"old2_l_pd"                      REAL
   ,"old3_l_pd"                      REAL
   ,"old1_b_va"                      TEXT
   ,"old2_b_va"                      TEXT
   ,"old3_b_va"                      TEXT
   ,"old1_b_pd"                      REAL
   ,"old2_b_pd"                      REAL
   ,"old3_b_pd"                      REAL
   ,"old1_ct_selection"              TEXT
   ,"old2_ct_selection"              TEXT
   ,"old3_ct_selection"              TEXT
   ,"old1_ct_fv_exo_p"               TEXT
   ,"old2_ct_fv_exo_p"               TEXT
   ,"old3_ct_fv_exo_p"               TEXT
   ,"old1_ct_fv_eso_p"               TEXT
   ,"old2_ct_fv_eso_p"               TEXT
   ,"old3_ct_fv_eso_p"               TEXT
   ,"old1_ct_nv_exo_p"               TEXT
   ,"old2_ct_nv_exo_p"               TEXT
   ,"old3_ct_nv_exo_p"               TEXT
   ,"old1_ct_nv_eso_p"               TEXT
   ,"old2_ct_nv_eso_p"               TEXT
   ,"old3_ct_nv_eso_p"               TEXT
   ,"old1_ct_fv_exo_t_e"             TEXT
   ,"old2_ct_fv_exo_t_e"             TEXT
   ,"old3_ct_fv_exo_t_e"             TEXT
   ,"old1_ct_fv_exo_t_p"             TEXT
   ,"old2_ct_fv_exo_t_p"             TEXT
   ,"old3_ct_fv_exo_t_p"             TEXT
   ,"old1_ct_fv_eso_t_e"             TEXT
   ,"old2_ct_fv_eso_t_e"             TEXT
   ,"old3_ct_fv_eso_t_e"             TEXT
   ,"old1_ct_fv_eso_t_p"             TEXT
   ,"old2_ct_fv_eso_t_p"             TEXT
   ,"old3_ct_fv_eso_t_p"             TEXT
   ,"old1_ct_nv_exo_t_e"             TEXT
   ,"old2_ct_nv_exo_t_e"             TEXT
   ,"old3_ct_nv_exo_t_e"             TEXT
   ,"old1_ct_nv_exo_t_p"             TEXT
   ,"old2_ct_nv_exo_t_p"             TEXT
   ,"old3_ct_nv_exo_t_p"             TEXT
   ,"old1_ct_nv_eso_t_e"             TEXT
   ,"old2_ct_nv_eso_t_e"             TEXT
   ,"old3_ct_nv_eso_t_e"             TEXT
   ,"old1_ct_nv_eso_t_p"             TEXT
   ,"old2_ct_nv_eso_t_p"             TEXT
   ,"old3_ct_nv_eso_t_p"             TEXT
   ,"old1_ct_fv_hp_e"                TEXT
   ,"old2_ct_fv_hp_e"                TEXT
   ,"old3_ct_fv_hp_e"                TEXT
   ,"old1_ct_fv_hp_p"                TEXT
   ,"old2_ct_fv_hp_p"                TEXT
   ,"old3_ct_fv_hp_p"                TEXT
   ,"old1_ct_fv_ht_e"                TEXT
   ,"old2_ct_fv_ht_e"                TEXT
   ,"old3_ct_fv_ht_e"                TEXT
   ,"old1_ct_fv_ht_p"                TEXT
   ,"old2_ct_fv_ht_p"                TEXT
   ,"old3_ct_fv_ht_p"                TEXT
   ,"old1_ct_nv_hp_e"                TEXT
   ,"old2_ct_nv_hp_e"                TEXT
   ,"old3_ct_nv_hp_e"                TEXT
   ,"old1_ct_nv_hp_p"                TEXT
   ,"old2_ct_nv_hp_p"                TEXT
   ,"old3_ct_nv_hp_p"                TEXT
   ,"old1_ct_nv_ht_e"                TEXT
   ,"old2_ct_nv_ht_e"                TEXT
   ,"old3_ct_nv_ht_e"                TEXT
   ,"old1_ct_nv_ht_p"                TEXT
   ,"old2_ct_nv_ht_p"                TEXT
   ,"old3_ct_nv_ht_p"                TEXT
   ,"old1_mr_selection"              TEXT
   ,"old2_mr_selection"              TEXT
   ,"old3_mr_selection"              TEXT
   ,"old1_mr_fv_exo_p"               TEXT
   ,"old2_mr_fv_exo_p"               TEXT
   ,"old3_mr_fv_exo_p"               TEXT
   ,"old1_mr_fv_eso_p"               TEXT
   ,"old2_mr_fv_eso_p"               TEXT
   ,"old3_mr_fv_eso_p"               TEXT
   ,"old1_mr_nv_exo_p"               TEXT
   ,"old2_mr_nv_exo_p"               TEXT
   ,"old3_mr_nv_exo_p"               TEXT
   ,"old1_mr_nv_eso_p"               TEXT
   ,"old2_mr_nv_eso_p"               TEXT
   ,"old3_mr_nv_eso_p"               TEXT
   ,"old1_mr_fv_exo_t_e"             TEXT
   ,"old2_mr_fv_exo_t_e"             TEXT
   ,"old3_mr_fv_exo_t_e"             TEXT
   ,"old1_mr_fv_exo_t_p"             TEXT
   ,"old2_mr_fv_exo_t_p"             TEXT
   ,"old3_mr_fv_exo_t_p"             TEXT
   ,"old1_mr_fv_eso_t_e"             TEXT
   ,"old2_mr_fv_eso_t_e"             TEXT
   ,"old3_mr_fv_eso_t_e"             TEXT
   ,"old1_mr_fv_eso_t_p"             TEXT
   ,"old2_mr_fv_eso_t_p"             TEXT
   ,"old3_mr_fv_eso_t_p"             TEXT
   ,"old1_mr_nv_exo_t_e"             TEXT
   ,"old2_mr_nv_exo_t_e"             TEXT
   ,"old3_mr_nv_exo_t_e"             TEXT
   ,"old1_mr_nv_exo_t_p"             TEXT
   ,"old2_mr_nv_exo_t_p"             TEXT
   ,"old3_mr_nv_exo_t_p"             TEXT
   ,"old1_mr_nv_eso_t_e"             TEXT
   ,"old2_mr_nv_eso_t_e"             TEXT
   ,"old3_mr_nv_eso_t_e"             TEXT
   ,"old1_mr_nv_eso_t_p"             TEXT
   ,"old2_mr_nv_eso_t_p"             TEXT
   ,"old3_mr_nv_eso_t_p"             TEXT
   ,"old1_mr_fv_hp_e"                TEXT
   ,"old2_mr_fv_hp_e"                TEXT
   ,"old3_mr_fv_hp_e"                TEXT
   ,"old1_mr_fv_hp_p"                TEXT
   ,"old2_mr_fv_hp_p"                TEXT
   ,"old3_mr_fv_hp_p"                TEXT
   ,"old1_mr_nv_hp_e"                TEXT
   ,"old2_mr_nv_hp_e"                TEXT
   ,"old3_mr_nv_hp_e"                TEXT
   ,"old1_mr_nv_hp_p"                TEXT
   ,"old2_mr_nv_hp_p"                TEXT
   ,"old3_mr_nv_hp_p"                TEXT
   ,"patient_r_pd"                   REAL
   ,"patient_l_pd"                   REAL
   ,"patient_b_pd"                   REAL
   ,"anam_remarks"                   TEXT
   ,"anam_unva_r_fv"                 TEXT
   ,"anam_unva_r_fv_cm"              TEXT
   ,"anam_unva_r_nv_j"               TEXT
   ,"anam_unva_l_fv"                 TEXT
   ,"anam_unva_l_fv_cm"              TEXT
   ,"anam_unva_l_nv_j"               TEXT
   ,"anam_medicine"                  TEXT
   ,"anam_allergy"                   TEXT
   ,"anam_f_illness"                 TEXT
   ,"anam_p_treat"                   TEXT
   ,"anam_l_eye"                     TEXT
   ,"anam_c_lens"                    TEXT
   ,"anam_medicine_rem"              TEXT
   ,"anam_allergy_rem"               TEXT
   ,"anam_f_illness_rem"             TEXT
   ,"anam_p_treat_rem"               TEXT
   ,"anam_l_eye_rem"                 TEXT
   ,"anam_c_lens_rem"                TEXT
   ,"anam_c_lens_type"               TEXT
   ,"anam_stop_before"               TEXT
   ,"anam_start_before"              TEXT
   ,"obj_r_sph"                      TEXT
   ,"obj_r_cyl"                      TEXT
   ,"obj_r_ax"                       INTEGER
   ,"obj_r_reflax"                   TEXT
   ,"obj_l_sph"                      TEXT
   ,"obj_l_cyl"                      TEXT
   ,"obj_l_ax"                       INTEGER
   ,"obj_l_reflax"                   TEXT
   ,"obj_w_r_sph"                    TEXT
   ,"obj_w_r_cyl"                    TEXT
   ,"obj_w_r_ax"                     INTEGER
   ,"obj_w_r_reflax"                 TEXT
   ,"obj_w_l_sph"                    TEXT
   ,"obj_w_l_cyl"                    TEXT
   ,"obj_w_l_ax"                     INTEGER
   ,"obj_w_l_reflax"                 TEXT
   ,"obj_k_r_dpt1"                   REAL
   ,"obj_k_r_dpt2"                   REAL
   ,"obj_k_r_mm1"                    REAL
   ,"obj_k_r_mm2"                    REAL
   ,"obj_k_r_mer1"                   REAL
   ,"obj_k_r_mer2"                   REAL
   ,"obj_k_r_dis"                    REAL
   ,"obj_k_l_dpt1"                   REAL
   ,"obj_k_l_dpt2"                   REAL
   ,"obj_k_l_mm1"                    REAL
   ,"obj_k_l_mm2"                    REAL
   ,"obj_k_l_mer1"                   REAL
   ,"obj_k_l_mer2"                   REAL
   ,"obj_k_l_dis"                    REAL
   ,"obj_cor_map"                    TEXT
   ,"obj_r_cor_map"                  TEXT
   ,"obj_l_cor_map"                  TEXT
   ,"sub_r_sph"                      TEXT
   ,"sub_r_cyl"                      TEXT
   ,"sub_r_ax"                       INTEGER
   ,"sub_r_prish"                    REAL
   ,"sub_r_baseh"                    TEXT
   ,"sub_r_prisv"                    REAL
   ,"sub_r_basev"                    TEXT
   ,"sub_r_va"                       TEXT
   ,"sub_r_j"                        TEXT
   ,"sub_r_ph"                       TEXT
   ,"sub_l_sph"                      TEXT
   ,"sub_l_cyl"                      TEXT
   ,"sub_l_ax"                       INTEGER
   ,"sub_l_prish"                    REAL
   ,"sub_l_baseh"                    TEXT
   ,"sub_l_prisv"                    REAL
   ,"sub_l_basev"                    TEXT
   ,"sub_l_va"                       TEXT
   ,"sub_l_j"                        TEXT
   ,"sub_l_ph"                       TEXT
   ,"sub_b_va"                       TEXT
   ,"sub_b_pd"                       REAL
   ,"sub_f_r_sph"                    TEXT
   ,"sub_f_r_cyl"                    TEXT
   ,"sub_f_r_ax"                     INTEGER
   ,"sub_f_r_prish"                  REAL
   ,"sub_f_r_baseh"                  TEXT
   ,"sub_f_r_prisv"                  REAL
   ,"sub_f_r_basev"                  TEXT
   ,"sub_f_r_va"                     TEXT
   ,"sub_f_r_j"                      TEXT
   ,"sub_f_r_far_pd"                 REAL
   ,"sub_f_r_near_pd"                REAL
   ,"sub_f_l_sph"                    TEXT
   ,"sub_f_l_cyl"                    TEXT
   ,"sub_f_l_ax"                     INTEGER
   ,"sub_f_l_prish"                  REAL
   ,"sub_f_l_baseh"                  TEXT
   ,"sub_f_l_prisv"                  REAL
   ,"sub_f_l_basev"                  TEXT
   ,"sub_f_l_va"                     TEXT
   ,"sub_f_l_j"                      TEXT
   ,"sub_f_l_far_pd"                 REAL
   ,"sub_f_l_near_pd"                REAL
   ,"sub_f_b_va"                     TEXT
   ,"sub_f_b_far_pd"                 REAL
   ,"sub_f_b_near_pd"                REAL
   ,"sub_r_read"                     TEXT
   ,"sub_r_int"                      TEXT
   ,"sub_r_bif"                      TEXT
   ,"sub_r_mul"                      TEXT
   ,"sub_l_read"                     TEXT
   ,"sub_l_int"                      TEXT
   ,"sub_l_bif"                      TEXT
   ,"sub_l_mul"                      TEXT
   ,"sub_r_add_j"                    TEXT
   ,"sub_l_add_j"                    TEXT
   ,"sub_r_add_at"                   REAL
   ,"sub_l_add_at"                   REAL
   ,"sub_r_green"                    TEXT
   ,"sub_r_equal"                    TEXT
   ,"sub_r_red"                      TEXT
   ,"sub_l_green"                    TEXT
   ,"sub_l_equal"                    TEXT
   ,"sub_l_red"                      TEXT
   ,"bino_ct_selection"              TEXT
   ,"bino_ct_fv_exo_p"               TEXT
   ,"bino_ct_fv_eso_p"               TEXT
   ,"bino_ct_nv_exo_p"               TEXT
   ,"bino_ct_nv_eso_p"               TEXT
   ,"bino_ct_fv_exo_t_e"             TEXT
   ,"bino_ct_fv_eso_t_e"             TEXT
   ,"bino_ct_fv_exo_t_p"             TEXT
   ,"bino_ct_fv_eso_t_p"             TEXT
   ,"bino_ct_nv_exo_t_e"             TEXT
   ,"bino_ct_nv_eso_t_e"             TEXT
   ,"bino_ct_nv_exo_t_p"             TEXT
   ,"bino_ct_nv_eso_t_p"             TEXT
   ,"bino_ct_fv_hp_e"                TEXT
   ,"bino_ct_fv_hp_p"                TEXT
   ,"bino_ct_nv_hp_e"                TEXT
   ,"bino_ct_nv_hp_p"                TEXT
   ,"bino_ct_fv_ht_e"                TEXT
   ,"bino_ct_fv_ht_p"                TEXT
   ,"bino_ct_nv_ht_e"                TEXT
   ,"bino_ct_nv_ht_p"                TEXT
   ,"bino_mw_selection"              TEXT
   ,"bino_mw_exo"                    TEXT
   ,"bino_mw_eso"                    TEXT
   ,"bino_mw_hp_e"                   TEXT
   ,"bino_mw_hp_p"                   TEXT
   ,"bino_mr_h_with"                 TEXT
   ,"bino_mr_h_no"                   TEXT
   ,"bino_mt_v_with"                 TEXT
   ,"bino_mr_v_no"                   TEXT
   ,"bino_ocular"                    TEXT
   ,"bino_rg_selection"              TEXT
   ,"bino_rg_supp_eye"               TEXT
   ,"bino_rg_prish"                  REAL
   ,"bino_rg_baseh"                  TEXT
   ,"bino_rg_prisv"                  REAL
   ,"bino_rg_basev"                  TEXT
   ,"bino_fr_fv_in_b"                TEXT
   ,"bino_fr_fv_in_r"                TEXT
   ,"bino_fr_fv_out_b"               TEXT
   ,"bino_fr_fv_out_r"               TEXT
   ,"bino_fr_nv_in_b"                TEXT
   ,"bino_fr_nv_in_r"                TEXT
   ,"bino_fr_nv_out_b"               TEXT
   ,"bino_fr_nv_out_r"               TEXT
   ,"bino_acc_r"                     TEXT
   ,"bino_acc_l"                     TEXT
   ,"bino_st_fly"                    TEXT
   ,"bino_st_cir_9"                  TEXT
   ,"bino_st_cir_3"                  TEXT
   ,"bino_cnp_cm"                    REAL
   ,"bino_cnp_eye"                   TEXT
   ,"bio_pupil_diam"                 REAL
   ,"bio_cornia_diam"                REAL
   ,"bio_eyelid_distance"            REAL
   ,"bio_eyelid_tens"                TEXT
   ,"bio_eyes_color"                 TEXT
   ,"bio_shirmer_r"                  TEXT
   ,"bio_shirmer_l"                  TEXT
   ,"bio_shirmer_r_mm"               REAL
   ,"bio_shirmer_l_mm"               REAL
   ,"bio_r_but"                      TEXT
   ,"bio_l_but"                      TEXT
   ,"bio_r_iop"                      REAL
   ,"bio_l_iop"                      REAL
   ,"bio_r_lens"                     TEXT
   ,"bio_l_lens"                     TEXT
   ,"bio_r_cornia"                   TEXT
   ,"bio_l_cornia"                   TEXT
   ,"bio_r_lach"                     TEXT
   ,"bio_l_lach"                     TEXT
   ,"bio_r_limbus"                   TEXT
   ,"bio_l_limbus"                   TEXT
   ,"bio_r_up_eyelid"                TEXT
   ,"bio_l_up_eyelid"                TEXT
   ,"bio_r_down_eyelid"              TEXT
   ,"bio_l_down_eyelid"              TEXT
   ,"fun_r_macula"                   TEXT
   ,"fun_l_macula"                   TEXT
   ,"fun_r_blood"                    TEXT
   ,"fun_l_blood"                    TEXT
   ,"fun_r_diska"                    TEXT
   ,"fun_l_diska"                    TEXT
   ,"fun_r_pupil"                    TEXT
   ,"fun_l_pupil"                    TEXT
   ,"amsler_grid"                    TEXT
   ,"old1_r_basev"                   TEXT
   ,"old2_r_basev"                   TEXT
   ,"old3_r_basev"                   TEXT
   ,"ob_right_se"                    REAL
   ,"ob_left_se"                     REAL
   ,"sb_right_fa"                    TEXT
   ,"sb_right_fa_add"                REAL
   ,"sb_left_fa"                     TEXT
   ,"sb_left_fa_add"                 REAL
   ,"sb_mid_fa"                      TEXT
   ,"sb_mid_fa_add"                  REAL
   ,"add_right_fcc"                  TEXT
   ,"add_left_fcc"                   TEXT
   ,"test_board"                     TEXT
   ,"test_remark"                    TEXT
   ,"dominant_eye"                   TEXT
   ,"add_cm1"                        REAL
   ,"add_cm2"                        REAL
   ,"add_cm3"                        REAL
   ,"add_cm4"                        REAL
   ,"add_right_j"                    TEXT
   ,"add_left_j"                     TEXT
   ,"bino_mr_h_addw"                 TEXT
   ,"bino_mr_h_addn"                 TEXT
   ,"bino_mr_v_addw"                 TEXT
   ,"bino_mr_v_addn"                 TEXT
   ,"ishihara_test"                  TEXT
   ,"anam_stop_before_p"             TEXT
   ,"anam_start_before_p"            TEXT
   ,"amsler_r_ok"                    TEXT
   ,"amsler_l_ok"                    TEXT
   ,"ishihara_rem"                   TEXT
   ,"sight_field"                    TEXT
   ,"subjective_remarks"             TEXT
   ,"bino_remarks"                   TEXT
   ,"old1_ct_hp_type"                TEXT
   ,"old2_ct_hp_type"                TEXT
   ,"old3_ct_hp_type"                TEXT
   ,"old1_ct_ht_type"                TEXT
   ,"old2_ct_ht_type"                TEXT
   ,"old3_ct_ht_type"                TEXT
   ,"bino_ct_hp_type"                TEXT
   ,"bino_ct_ht_type"                TEXT
   ,"old1_pa"                        REAL
   ,"old1_bvd"                       REAL
   ,"old1_ffa"                       REAL
   ,"old1_df"                        REAL
   ,"old1_dn"                        REAL
   ,"sub_f_pa"                       REAL
   ,"sub_f_bvd"                      REAL
   ,"sub_f_ffa"                      REAL
   ,"sub_f_df"                       REAL
   ,"sub_f_dn"                       REAL
);


CREATE TABLE "optic_eye_tests" (
    "code"                           INTEGER PRIMARY KEY AUTOINCREMENT
   ,"branch_code"                    INTEGER
   ,"account_code"                   INTEGER
   ,"account_type"                   TEXT NOT NULL
   ,"test_date"                      TEXT
   ,"dominant_eye"                   TEXT
   ,"test_reason"                    TEXT
   ,"iop_right"                      REAL
   ,"iop_left"                       REAL
   ,"or_right_sph"                   TEXT
   ,"or_right_cyl"                   TEXT
   ,"or_right_ax"                    INTEGER
   ,"or_right_pris"                  REAL
   ,"or_right_base"                  TEXT
   ,"or_right_va"                    TEXT
   ,"or_right_add"                   TEXT
   ,"or_left_sph"                    TEXT
   ,"or_left_cyl"                    TEXT
   ,"or_left_ax"                     INTEGER
   ,"or_left_pris"                   REAL
   ,"or_left_base"                   TEXT
   ,"or_left_va"                     TEXT
   ,"or_left_add"                    TEXT
   ,"or_mid_va"                      TEXT
   ,"ob_right_sph"                   TEXT
   ,"ob_right_cyl"                   TEXT
   ,"ob_right_ax"                    INTEGER
   ,"ob_right_se"                    REAL
   ,"ob_left_sph"                    TEXT
   ,"ob_left_cyl"                    TEXT
   ,"ob_left_ax"                     INTEGER
   ,"ob_left_se"                     REAL
   ,"sb_right_fa"                    TEXT
   ,"sb_right_fa_add"                REAL
   ,"sb_right_sph"                   TEXT
   ,"sb_right_cyl"                   TEXT
   ,"sb_right_ax"                    INTEGER
   ,"sb_right_pris"                  REAL
   ,"sb_right_base"                  TEXT
   ,"sb_right_va"                    TEXT
   ,"sb_right_near_pd"               REAL
   ,"sb_right_far_pd"                REAL
   ,"sb_right_ph"                    TEXT
   ,"sb_left_fa"                     TEXT
   ,"sb_left_fa_add"                 REAL
   ,"sb_left_sph"                    TEXT
   ,"sb_left_cyl"                    TEXT
   ,"sb_left_ax"                     INTEGER
   ,"sb_left_pris"                   REAL
   ,"sb_left_base"                   TEXT
   ,"sb_left_va"                     TEXT
   ,"sb_left_near_pd"                REAL
   ,"sb_left_far_pd"                 REAL
   ,"sb_left_ph"                     TEXT
   ,"sb_mid_fa"                      TEXT
   ,"sb_mid_fa_add"                  REAL
   ,"sb_mid_va"                      TEXT
   ,"add_right_fcc"                  TEXT
   ,"add_right_read"                 TEXT
   ,"add_right_int"                  TEXT
   ,"add_right_bif"                  TEXT
   ,"add_right_mul"                  TEXT
   ,"add_right_j"                    TEXT
   ,"add_left_fcc"                   TEXT
   ,"add_left_read"                  TEXT
   ,"add_left_int"                   TEXT
   ,"add_left_bif"                   TEXT
   ,"add_left_mul"                   TEXT
   ,"add_left_j"                     TEXT
   ,"test_board"                     TEXT
   ,"test_remark"                    TEXT
   ,"is_active"                      TEXT NOT NULL DEFAULT '1'
   ,"last_action"                    TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
   ,"tester_code"                    INTEGER
   ,"sb_mid_near_pd"                 REAL
   ,"sb_mid_far_pd"                  REAL
   ,"add_cm1"                        REAL
   ,"add_cm2"                        REAL
   ,"add_cm3"                        REAL
   ,"add_cm4"                        REAL
);


CREATE TABLE "optic_glasses_presc" (
    "code"                           INTEGER PRIMARY KEY AUTOINCREMENT
   ,"branch_code"                    INTEGER
   ,"account_code"                   INTEGER
   ,"account_type"                   TEXT NOT NULL
   ,"presc_date"                     TEXT
   ,"dominant_eye"                   TEXT
   ,"glasses_function"               TEXT
   ,"right_fv"                       TEXT
   ,"right_fv_add"                   TEXT
   ,"right_sph"                      TEXT
   ,"right_cyl"                      TEXT
   ,"right_ax"                       INTEGER
   ,"right_pris"                     REAL
   ,"right_base"                     TEXT
   ,"right_va"                       TEXT
   ,"right_read"                     TEXT
   ,"right_int"                      TEXT
   ,"right_bif"                      TEXT
   ,"right_mul"                      TEXT
   ,"right_high"                     TEXT
   ,"right_pd"                       REAL
   ,"left_fv"                        TEXT
   ,"left_fv_add"                    TEXT
   ,"left_sph"                       TEXT
   ,"left_cyl"                       TEXT
   ,"left_ax"                        INTEGER
   ,"left_pris"                      REAL
   ,"left_base"                      TEXT
   ,"left_va"                        TEXT
   ,"left_read"                      TEXT
   ,"left_int"                       TEXT
   ,"left_bif"                       TEXT
   ,"left_mul"                       TEXT
   ,"left_high"                      TEXT
   ,"left_pd"                        REAL
   ,"mid_va"                          TEXT
   ,"pd_near"                        REAL
   ,"pd_far"                         REAL
   ,"lens_supplier"                  TEXT
   ,"lens_mater"                     TEXT
   ,"lens_model_right"               TEXT
   ,"lens_model_left"                TEXT
   ,"lens_coat"                      TEXT
   ,"lens_color"                     TEXT
   ,"lens_diameter"                  REAL
   ,"lens_segment"                   TEXT
   ,"frame_manuf"                    TEXT
   ,"frame_supplier"                 TEXT
   ,"frame_model"                    TEXT
   ,"frame_color"                    TEXT
   ,"frame_size"                     TEXT
   ,"frame_length"                   TEXT
   ,"bag_number"                     TEXT
   ,"promise_to_date"                TEXT
   ,"delivere_date"                  TEXT
   ,"presc_remark"                   TEXT
   ,"payments_rule"                  TEXT
   ,"is_active"                      TEXT NOT NULL DEFAULT '1'
   ,"last_action"                    TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
   ,"tester_code"                    INTEGER
   ,"advisor_code"                   INTEGER
   ,"giver_code"                     INTEGER
   ,"tech_code"                      INTEGER
   ,"addition_type"                  TEXT
   ,"add_cm1"                        REAL
   ,"add_cm2"                        REAL
   ,"add_cm3"                        REAL
   ,"add_cm4"                        REAL
   ,"lab_status"                     TEXT
   ,"work_in_cm"                     TEXT
   ,"connection_code"                INTEGER
   ,"lab_status_sent"                TEXT
   ,"frame_code"                     INTEGER
   ,"right_lens_code"                INTEGER
   ,"left_lens_code"                 INTEGER
   ,"right_lens_price"               REAL
   ,"left_lens_price"                REAL
   ,"supplements_price"              REAL
   ,"frame_price"                    REAL
   ,"order_iner_priority"            INTEGER
   ,"discount_sum"                   REAL
   ,"total_sum"                      REAL
   ,"order_status"                   INTEGER
   ,"right_in_stock"                 TEXT
   ,"left_in_stock"                  TEXT
   ,"right_lens_type"                TEXT
   ,"left_lens_type"                 TEXT
   ,"right_diam"                     REAL
   ,"left_diam"                      REAL
   ,"manuf_branch"                   INTEGER
   ,"supply_branch"                  INTEGER
   ,"current_branch"                 INTEGER
   ,"order_type"                     TEXT
   ,"confirmation_date"              TEXT
   ,"end_of_warranty"                TEXT
   ,"frame_supply_by"                TEXT
   ,"has_confirmation"               TEXT
   ,"num_payments"                   INTEGER
   ,"advance_sum"                    REAL
   ,"lens_color_at"                  TEXT
   ,"order_remarks"                  TEXT
   ,"right_add"                      REAL
   ,"left_add"                       REAL
   ,"right_decent"                   REAL
   ,"left_decent"                    REAL
   ,"right_sbase"                    REAL
   ,"left_sbase"                     REAL
   ,"lens_group"                     TEXT
   ,"frame_width"                    REAL
   ,"frame_height"                   REAL
   ,"frame_bridge"                   REAL
   ,"frame_shape"                    TEXT
   ,"edge_width"                     REAL
   ,"edge_mm"                        REAL
   ,"screw1_x"                        REAL
   ,"screw2_x"                        REAL
   ,"screw3_x"                        REAL
   ,"screw4_x"                        REAL
   ,"screw1_y"                        REAL
   ,"screw2_y"                        REAL
   ,"screw3_y"                        REAL
   ,"screw4_y"                        REAL
   ,"sms_sent"                       TEXT
   ,"frame_discount"                 REAL
   ,"rlens_discount"                 REAL
   ,"llens_discount"                 REAL
   ,"right_s_base"                   REAL
   ,"left_s_base"                    REAL
   ,"disconnect_finance"             TEXT
   ,"send_order"                     TEXT
   ,"num_order"                      INTEGER
   ,"order_qty"                      INTEGER
   ,"cost_buying_r"                  REAL
   ,"cost_buying_l"                  REAL
   ,"multi_pa"                        TEXT
   ,"multi_bvd"                       TEXT
   ,"multi_ffa"                       TEXT
   ,"multi_df"                        TEXT
   ,"multi_dn"                        TEXT
);


