name: Release Build

on:
  push:
    tags:
      - 'v*.*.*'

# Add permissions for the workflow
permissions:
  contents: write
  packages: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      release_id: ${{ steps.create_release.outputs.id }}
    steps:
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: true  # Keep as draft until all builds complete
          prerelease: false
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    needs: create-release
    runs-on: macos-latest
    permissions:
      contents: write
    strategy:
      matrix:
        arch: [arm64, x64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm ci

      - name: Build for macOS ${{ matrix.arch }}
        run: npm run build:mac:${{ matrix.arch }}
        env:
          NODE_ENV: production
          NODE_OPTIONS: --max-old-space-size=4096
          CSC_IDENTITY_AUTO_DISCOVERY: false
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Upload macOS ${{ matrix.arch }} artifacts
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.VERSION }}
          files: |
            release/Prysm-darwin-${{ matrix.arch }}-${{ steps.version.outputs.VERSION }}.zip
            release/latest-mac.yml

  build-windows:
    needs: create-release
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm ci

      - name: Build for Windows
        run: npm run build:win
        env:
          NODE_ENV: production
          NODE_OPTIONS: --max-old-space-size=4096
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version
        id: version
        shell: bash
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Upload Windows artifacts
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.VERSION }}
          files: |
            release/Prysm-Setup-${{ steps.version.outputs.VERSION }}.exe
            release/latest.yml

  finalize-release:
    needs: [build-macos, build-windows]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Update release notes
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const version = context.ref.replace('refs/tags/v', '');
            const { data: release } = await github.rest.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: `v${version}`
            });
            
            await github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: release.id,
              body: `## 🎉 Release v${version}
            
            ### Downloads
            - **macOS Apple Silicon (M1/M2/M3)**: \`Prysm-darwin-arm64-${version}.zip\`
            - **macOS Intel**: \`Prysm-darwin-x64-${version}.zip\`
            - **Windows**: \`Prysm-Setup-${version}.exe\`
            
            ### Auto-Update Support
            This release includes automatic update support! The app will notify you when new versions are available.
            
            ### Installation
            
            #### macOS
            1. Download the appropriate ZIP for your Mac (Apple Silicon or Intel)
            2. Extract the ZIP file
            3. Move Prysm.app to your Applications folder
            4. **First time opening**: Right-click Prysm.app → "Open" → "Open" (bypasses Gatekeeper)
            5. **Alternative**: Run \`xattr -cr /Applications/Prysm.app\` in Terminal
            
            #### Windows
            1. Download \`Prysm-Setup-${version}.exe\`
            2. Run the installer
            3. Follow the installation wizard
            4. The app will auto-update in the background
            
            ### What's Changed
            See the commits for detailed changes.
            
            ---
            
            **Full Changelog**: https://github.com/${context.repo.owner}/${context.repo.repo}/compare/v${parseFloat(version) - 0.1}...v${version}`,
              draft: false,  // Publish the release (required for electron-updater)
              make_latest: true  // Mark as latest release
            });

